// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1_bKTvaISqaPV45UsPju2x1yjhqN-6ck',
    appId: '1:766729968420:web:41488fbaea0ff2670cf1b1',
    messagingSenderId: '766729968420',
    projectId: 'herble-efae7',
    authDomain: 'herble-efae7.firebaseapp.com',
    storageBucket: 'herble-efae7.appspot.com',
    measurementId: 'G-D6SZXC3CS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9lfAdaZa8zzrHoTh41dG2Onctjc_isJc',
    appId: '1:766729968420:android:122f4ced4c312a130cf1b1',
    messagingSenderId: '766729968420',
    projectId: 'herble-efae7',
    storageBucket: 'herble-efae7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5h6Vo2I-X3Xix8ENAY82x1FtFt8zsAnU',
    appId: '1:766729968420:ios:83a961ae9b6022d30cf1b1',
    messagingSenderId: '766729968420',
    projectId: 'herble-efae7',
    storageBucket: 'herble-efae7.appspot.com',
    iosClientId: '766729968420-l5ei3ka6lqf2hscjgm6le4i93r1itmfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.herble',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5h6Vo2I-X3Xix8ENAY82x1FtFt8zsAnU',
    appId: '1:766729968420:ios:83a961ae9b6022d30cf1b1',
    messagingSenderId: '766729968420',
    projectId: 'herble-efae7',
    storageBucket: 'herble-efae7.appspot.com',
    iosClientId: '766729968420-l5ei3ka6lqf2hscjgm6le4i93r1itmfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.herble',
  );
}
